### ISSUE TITLE
建议：信息获取阶段优化

### ISSUE THREAD

**Issue by yyjazsf** [MagicCube/tensorflow-rex-run#1]
是否考虑将AI的信息获取做成 动态画面捕获，然后通过操作按键的形式 玩游戏。毕竟通过修改游戏源码实现AI玩游戏通用性不大

**Comment by jschyz** [comment]
坐等

**Comment by MagicCube** [comment]
当然可以啦，这就是强化学习嘛，通过  Canvas 可以直接拿到图像，通过 TensorFlow.js 可以轻松将图像通过 CNN 处理成 faltten 过的 feature，然后接下来的事情和之前的神经网络类似，也可以用强化学习训练。
