### ISSUE TITLE
Invalid URL in project description

### ISSUE THREAD

**Issue by Neamar** [MagicCube/tensorflow-rex-run#2]
The URL on top of Github repository should be https://magiccube.github.io/tensorflow-rex-run/neural-network.html :)

![image](https://user-images.githubusercontent.com/536844/45757158-a187c000-bc1a-11e8-8f20-9d4e842d27ed.png)

I assume the repo was renamed at some point.

**Comment by MagicCube** [comment]
Thank you, bro!
